# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://sullivans.co
title: The Sullivans
email: info@sullivans.co
author: Sullivan
description: > # "Write an awesome description for your new site here. 
  The home site for information about The Sullivans. Both a directory and informational
  location for learning more.
copyright: 'Copyright &copy; 2020 Sullivans. All Rights Reserved.'
credits: 'Site Created and Developed by <a href="https://jonsully.net" target="_blank">Jon</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  # - title: github
  #   url: https://github.com/IronSummitMedia/startbootstrap
  # - title: linkedin
  #   url: 
