# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://sullivans.co
title: The Sullivans
email: info@sullivans.co
author: Sullivan
description: > 
  The home site for information about The Sullivans. Both a directory and informational
  location for learning more.
copyright: 'Copyright &copy; 2020 Sullivans. All Rights Reserved.'
credits: 'Site Created and Developed by <a href="https://jonsully.net" target="_blank">Jon</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
